import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Chat gpt",
  description: "Generated by create next app",
icons : {
  icon : "/chatgpt.png"
}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
